### ISSUE TITLE
As an admin, I want to create new roles so that I can assign resource policies to those roles

### ISSUE THREAD

**Issue by waiyan13** [techyangon/may-jls-ui#10]
## Acceptance Criteria

Feature: Role creation

    Scenario: the admin wants to create new role
        Given the role does not exist in the database
        When the admin enters the name of the role
        Then the role should be recorded and displayed

    Scenario: the admin wants to assign resource policies to the role
        Given the role exists
        When the admin assigns policies to the role
        Then the role page should be display resource name and allowed policies

## Tasks List

- [ ] Create table to display roles
- [ ] Create button to show role creation form
- [ ] Save the role to database and handle validation
- [ ] Create page to assign resource policies to specified role
- [ ] Save role and policies relations
