### ISSUE TITLE
As a user, I want to login so that I can see my dashboard

### ISSUE THREAD

**Issue by waiyan13** [techyangon/may-jls-ui#3]
## Acceptance Criteria

Feature: Authentication

    Scenario: when the user logs in
        Given the user has correct credentials
        When the user logs in
        Then the user should be redirected to dashboard

    Scenario: when the user logs in
        Given the user has incorrect credentials
        When the user logs in
        Then the user should be prompted with information
## Tasks List

- [ ] Check if the user is logged in
- [ ] Redirect to login page if the user is not logged in
- [ ] Deny navigation to private routes
- [ ] Clear local storage if access token is expired

**Comment by waiyan13** [comment]
Resolved by #4
