### ISSUE TITLE
As an admin, I want to create new resource so that I can manage said resource

### ISSUE THREAD

**Issue by waiyan13** [techyangon/may-jls-ui#5]
## Acceptance Criteria

Feature: Resource creation

    Scenario: The admin is at resource list page
        Given the admin wants to create new resource
        When the admin enter necessary details
        Then the resource should be created and displayed

## Tasks List

- [x] Create navigation link for resource page
- [ ] List all resources
- [ ] Add button to create resource
- [ ] Create request to create new resource

**Comment by waiyan13** [comment]
Closed because resources are not defined by users but by system design
